sudo: false

notifications:
  email: false

os:
  - osx

language: node_js
node_js: lts/*

env:
  matrix:
    - BOT=1
    - BOT=2
    - BOT=3
    - BOT=4
    - BOT=5
    - BOT=6
    - BOT=7
    - BOT=8
    - BOT=9
    - BOT=10

before_install:
  - export ELECTRON_NO_ATTACH_CONSOLE=1
  - node --version
  - npm --version

install:
  - npm ci

script:
  - npm test
