sudo: false

notifications:
  email: false

os:
  - osx

language: node_js
node_js: lts/*

env:
  matrix:
    - CODE_VERSION=insiders BOT=1
    - CODE_VERSION=insiders BOT=2
    - CODE_VERSION=insiders BOT=3
    - CODE_VERSION=insiders BOT=4
    - CODE_VERSION=insiders BOT=5
    - CODE_VERSION=insiders BOT=6
    - CODE_VERSION=insiders BOT=7
    - CODE_VERSION=insiders BOT=8
    - CODE_VERSION=insiders BOT=9
    - CODE_VERSION=insiders BOT=10
    - CODE_VERSION=stable BOT=1
    - CODE_VERSION=stable BOT=2
    - CODE_VERSION=stable BOT=3
    - CODE_VERSION=stable BOT=4
    - CODE_VERSION=stable BOT=5
    - CODE_VERSION=stable BOT=6
    - CODE_VERSION=stable BOT=7
    - CODE_VERSION=stable BOT=8
    - CODE_VERSION=stable BOT=9
    - CODE_VERSION=stable BOT=10

before_install:
  - export ELECTRON_NO_ATTACH_CONSOLE=1
  - node --version
  - npm --version

install:
  - npm ci

script:
  - npm test
